# Generated by Django 6.0.4 on 2026-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membershipapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='skills',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='areas_of_interest',
            field=models.CharField(blank=True, help_text='Which areas interest you most? (e.g., Health, Education, Emergency Relief, Youth)', max_length=300),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='city',
            field=models.CharField(blank=True, help_text='City where you live', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='contribution',
            field=models.TextField(blank=True, help_text='What skills, resources, or time can you contribute to the association?'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='Country where you currently live', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='education_level',
            field=models.CharField(choices=[('none', 'No Formal Education'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], default='bachelor', max_length=15),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('volunteer', 'Full-time Volunteer')], default='employed', max_length=15),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='List languages you speak (e.g., English, French, Swahili)', max_length=300),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='nationality',
            field=models.CharField(blank=True, help_text='Your country of citizenship', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='previous_volunteering',
            field=models.TextField(blank=True, help_text='Describe any previous volunteering or community service experience'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='professional_skills',
            field=models.TextField(blank=True, help_text='List your professional skills relevant to NGO work (e.g., project management, accounting, social work)'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How did you hear about us?', max_length=200),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='availability',
            field=models.CharField(blank=True, help_text='How much time can you commit? (e.g., 5 hours/week, weekends only)', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='motivation',
            field=models.TextField(help_text='Why do you want to join the Association for Mercy? What inspires you about our mission?'),
        ),
    ]
