# Generated by Django 6.0.5 on 2026-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_membershipapplication_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='account_created',
            field=models.BooleanField(default=False, help_text='Whether the applicant has created their account'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='signup_token',
            field=models.UUIDField(blank=True, help_text='Unique token for account creation after approval', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='signup_token_created_at',
            field=models.DateTimeField(blank=True, help_text='When the signup token was generated', null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='signup_token_used',
            field=models.BooleanField(default=False, help_text='Whether the signup token has been used'),
        ),
    ]
