# Generated by Django 6.0.5 on 2026-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_membershipapplication_account_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', help_text="Designates the user's role in the system.", max_length=15),
        ),
    ]
