# Generated by Django 6.0.5 on 2026-05-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload a supporting document (PDF, JPG, JPEG, PNG only)', upload_to='membership_documents/%Y/%m/')),
                ('document_type', models.CharField(help_text='e.g., Birth Certificate, National ID, CV, Certificate', max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.membershipapplication')),
            ],
            options={
                'verbose_name': 'Membership Document',
                'verbose_name_plural': 'Membership Documents',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
