# Generated by Django 6.0.5 on 2026-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_membershipdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('interview', 'Interview Scheduled')], default='pending', max_length=15),
        ),
    ]
