# Generated by Django 6.0.5 on 2026-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_membershipapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Professional profile photo (JPG, JPEG, PNG only, max 2MB)', null=True, upload_to='profile_pictures/'),
        ),
    ]
