# Generated by Django 6.0.5 on 2026-05-22 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_under_review', 'Application Under Review'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('document_uploaded', 'Document Uploaded'), ('invitation_sent', 'Invitation Sent'), ('account_created', 'Account Created'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('role_changed', 'Role Changed'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
