# Generated by Django 6.0.5 on 2026-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auditlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['status'], name='users_membe_status_be5b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['email'], name='users_membe_email_44c2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['submitted_at'], name='users_membe_submitt_c3e94f_idx'),
        ),
    ]
