# Generated by Django 6.0.5 on 2026-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this activity (recommended: 800x600px)', upload_to='activities/'),
        ),
    ]
