# Generated by Django 6.0.5 on 2026-05-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('beneficiaries', 'Beneficiaries'), ('donations', 'Donations'), ('donation_intents', 'Donation Intents'), ('programs', 'Programs'), ('membership_applications', 'Membership Applications'), ('users', 'Users')], max_length=30)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('print', 'Print')], max_length=10)),
                ('filters_applied', models.TextField(blank=True, help_text='JSON string of filters used')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-exported_at'],
            },
        ),
    ]
