# Generated by Django 6.0.5 on 2026-05-31 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['email'], name='beneficiari_email_82eb53_idx'),
        ),
    ]
