"""
Country data: names, flag emojis, and phone codes.
Used by public forms for nationality, country of residence, and phone fields.
"""
# African countries first (relevant to Cameroon-based NGO), then rest of world.
COUNTRIES = [
    # ── Africa ─────────────────────────────────────────────
    ('Cameroon', '🇨🇲 Cameroon', '+237'),
    ('Nigeria', '🇳🇬 Nigeria', '+234'),
    ('Chad', '🇹🇩 Chad', '+235'),
    ('Central African Republic', '🇨🇫 Central African Republic', '+236'),
    ('Gabon', '🇬🇦 Gabon', '+241'),
    ('Equatorial Guinea', '🇬🇶 Equatorial Guinea', '+240'),
    ('Congo', '🇨🇬 Congo', '+242'),
    ('DR Congo', '🇨🇩 DR Congo', '+243'),
    ('Angola', '🇦🇴 Angola', '+244'),
    ('Ghana', '🇬🇭 Ghana', '+233'),
    ('Ivory Coast', '🇨🇮 Ivory Coast', '+225'),
    ('Senegal', '🇸🇳 Senegal', '+221'),
    ('Mali', '🇲🇱 Mali', '+223'),
    ('Burkina Faso', '🇧🇫 Burkina Faso', '+226'),
    ('Benin', '🇧🇯 Benin', '+229'),
    ('Togo', '🇹🇬 Togo', '+228'),
    ('Niger', '🇳🇪 Niger', '+227'),
    ('Guinea', '🇬🇳 Guinea', '+224'),
    ('Sierra Leone', '🇸🇱 Sierra Leone', '+232'),
    ('Liberia', '🇱🇷 Liberia', '+231'),
    ('Gambia', '🇬🇲 Gambia', '+220'),
    ('Mauritania', '🇲🇷 Mauritania', '+222'),
    ('Morocco', '🇲🇦 Morocco', '+212'),
    ('Algeria', '🇩🇿 Algeria', '+213'),
    ('Tunisia', '🇹🇳 Tunisia', '+216'),
    ('Libya', '🇱🇾 Libya', '+218'),
    ('Egypt', '🇪🇬 Egypt', '+20'),
    ('Sudan', '🇸🇩 Sudan', '+249'),
    ('South Sudan', '🇸🇸 South Sudan', '+211'),
    ('Ethiopia', '🇪🇹 Ethiopia', '+251'),
    ('Kenya', '🇰🇪 Kenya', '+254'),
    ('Uganda', '🇺🇬 Uganda', '+256'),
    ('Tanzania', '🇹🇿 Tanzania', '+255'),
    ('Rwanda', '🇷🇼 Rwanda', '+250'),
    ('Burundi', '🇧🇮 Burundi', '+257'),
    ('Somalia', '🇸🇴 Somalia', '+252'),
    ('South Africa', '🇿🇦 South Africa', '+27'),
    ('Zimbabwe', '🇿🇼 Zimbabwe', '+263'),
    ('Zambia', '🇿🇲 Zambia', '+260'),
    ('Malawi', '🇲🇼 Malawi', '+265'),
    ('Mozambique', '🇲🇿 Mozambique', '+258'),
    ('Madagascar', '🇲🇬 Madagascar', '+261'),
    ('Namibia', '🇳🇦 Namibia', '+264'),
    ('Botswana', '🇧🇼 Botswana', '+267'),
    ('Lesotho', '🇱🇸 Lesotho', '+266'),
    ('Eswatini', '🇸🇿 Eswatini', '+268'),

    # ── Europe ─────────────────────────────────────────────
    ('France', '🇫🇷 France', '+33'),
    ('Belgium', '🇧🇪 Belgium', '+32'),
    ('Switzerland', '🇨🇭 Switzerland', '+41'),
    ('Germany', '🇩🇪 Germany', '+49'),
    ('United Kingdom', '🇬🇧 United Kingdom', '+44'),
    ('Italy', '🇮🇹 Italy', '+39'),
    ('Spain', '🇪🇸 Spain', '+34'),
    ('Portugal', '🇵🇹 Portugal', '+351'),
    ('Netherlands', '🇳🇱 Netherlands', '+31'),
    ('Sweden', '🇸🇪 Sweden', '+46'),
    ('Norway', '🇳🇴 Norway', '+47'),
    ('Denmark', '🇩🇰 Denmark', '+45'),
    ('Finland', '🇫🇮 Finland', '+358'),
    ('Ireland', '🇮🇪 Ireland', '+353'),
    ('Poland', '🇵🇱 Poland', '+48'),
    ('Ukraine', '🇺🇦 Ukraine', '+380'),
    ('Russia', '🇷🇺 Russia', '+7'),
    ('Turkey', '🇹🇷 Turkey', '+90'),
    ('Greece', '🇬🇷 Greece', '+30'),
    ('Austria', '🇦🇹 Austria', '+43'),

    # ── Americas ───────────────────────────────────────────
    ('United States', '🇺🇸 United States', '+1'),
    ('Canada', '🇨🇦 Canada', '+1'),
    ('Mexico', '🇲🇽 Mexico', '+52'),
    ('Brazil', '🇧🇷 Brazil', '+55'),
    ('Argentina', '🇦🇷 Argentina', '+54'),
    ('Colombia', '🇨🇴 Colombia', '+57'),
    ('Chile', '🇨🇱 Chile', '+56'),
    ('Peru', '🇵🇪 Peru', '+51'),
    ('Venezuela', '🇻🇪 Venezuela', '+58'),
    ('Haiti', '🇭🇹 Haiti', '+509'),
    ('Jamaica', '🇯🇲 Jamaica', '+1-876'),
    ('Cuba', '🇨🇺 Cuba', '+53'),

    # ── Asia & Middle East ─────────────────────────────────
    ('China', '🇨🇳 China', '+86'),
    ('India', '🇮🇳 India', '+91'),
    ('Japan', '🇯🇵 Japan', '+81'),
    ('South Korea', '🇰🇷 South Korea', '+82'),
    ('Philippines', '🇵🇭 Philippines', '+63'),
    ('Vietnam', '🇻🇳 Vietnam', '+84'),
    ('Thailand', '🇹🇭 Thailand', '+66'),
    ('Indonesia', '🇮🇩 Indonesia', '+62'),
    ('Malaysia', '🇲🇾 Malaysia', '+60'),
    ('Singapore', '🇸🇬 Singapore', '+65'),
    ('Pakistan', '🇵🇰 Pakistan', '+92'),
    ('Bangladesh', '🇧🇩 Bangladesh', '+880'),
    ('Saudi Arabia', '🇸🇦 Saudi Arabia', '+966'),
    ('United Arab Emirates', '🇦🇪 United Arab Emirates', '+971'),
    ('Qatar', '🇶🇦 Qatar', '+974'),
    ('Kuwait', '🇰🇼 Kuwait', '+965'),
    ('Lebanon', '🇱🇧 Lebanon', '+961'),
    ('Israel', '🇮🇱 Israel', '+972'),
    ('Jordan', '🇯🇴 Jordan', '+962'),

    # ── Oceania ────────────────────────────────────────────
    ('Australia', '🇦🇺 Australia', '+61'),
    ('New Zealand', '🇳🇿 New Zealand', '+64'),

    # ── Other ──────────────────────────────────────────────
    ('Other', '🌍 Other / Not Listed', ''),
]

# Lookup helpers
COUNTRY_CHOICES = [(c[0], c[1]) for c in COUNTRIES]
COUNTRY_CODE_MAP = {c[0]: c[2] for c in COUNTRIES if c[2]}


# ─── Areas of Interest (for membership form) ─────────────

AREA_OF_INTEREST_CHOICES = [
    ('health_medical', '🏥 Health & Medical Aid'),
    ('education_literacy', '📚 Education & Literacy'),
    ('emergency_relief', '🚨 Emergency Relief & Disaster Response'),
    ('food_security', '🌾 Food Security & Nutrition'),
    ('wash', '💧 Water, Sanitation & Hygiene (WASH)'),
    ('youth_empowerment', '🌟 Youth Empowerment'),
    ('women_empowerment', '👩🏿 Women\'s Empowerment'),
    ('child_protection', '👶 Child Protection & Welfare'),
    ('community_development', '🏘️ Community Development'),
    ('poverty_alleviation', '🤝 Poverty Alleviation'),
    ('orphan_care', '🏠 Orphan Care & Support'),
    ('elderly_care', '👴 Elderly Care'),
    ('disability_support', '♿ Disability Support'),
    ('refugee_support', '🫂 Refugee & IDP Support'),
    ('vocational_training', '🔧 Vocational Training & Skills Development'),
    ('agriculture', '🌱 Agriculture & Food Production'),
    ('environment', '🌍 Environmental Conservation'),
    ('peace_building', '☮️ Peace Building & Conflict Resolution'),
    ('human_rights', '✊ Human Rights Advocacy'),
    ('spiritual_care', '🙏 Spiritual & Pastoral Care'),
    ('microfinance', '💰 Microfinance & Economic Empowerment'),
    ('housing', '🏗️ Housing & Shelter'),
    ('legal_aid', '⚖️ Legal Aid & Justice'),
    ('counseling', '🧠 Counseling & Mental Health'),
    ('arts_culture', '🎨 Arts, Culture & Sports for Development'),
]
