# Generated by Django 6.0.4 on 2026-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationintent',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional information you would like to share'),
        ),
        migrations.AddField(
            model_name='donationintent',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='Country where you currently live', max_length=100),
        ),
        migrations.AddField(
            model_name='donationintent',
            name='currency',
            field=models.CharField(choices=[('XAF', 'XAF - Central African CFA Franc'), ('XOF', 'XOF - West African CFA Franc'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar'), ('NGN', 'NGN - Nigerian Naira'), ('GHC', 'GHS - Ghanaian Cedi'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('OTHER', 'Other')], default='XAF', max_length=5),
        ),
        migrations.AddField(
            model_name='donationintent',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='one_time', max_length=10),
        ),
        migrations.AddField(
            model_name='donationintent',
            name='nationality',
            field=models.CharField(blank=True, help_text='Your country of citizenship', max_length=100),
        ),
        migrations.AddField(
            model_name='donationintent',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='either', help_text='How would you like us to contact you?', max_length=10),
        ),
    ]
