# Generated by Django 6.0.5 on 2026-05-31 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationintent_additional_notes_and_more'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_email'], name='donations_d_donor_e_914ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['program'], name='donations_d_program_747b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='donationintent',
            index=models.Index(fields=['status'], name='donations_d_status_10e35e_idx'),
        ),
        migrations.AddIndex(
            model_name='donationintent',
            index=models.Index(fields=['email'], name='donations_d_email_efc278_idx'),
        ),
        migrations.AddIndex(
            model_name='donationintent',
            index=models.Index(fields=['submitted_at'], name='donations_d_submitt_8b1342_idx'),
        ),
    ]
